#!/usr/bin/env python3
"""§D-OVERSPREAD ORDERING RED-TEAM — attack the hypothesized D1->D3->D5 causal stack.

READ-ONLY / EVAL-ONLY. Consumes ONLY banked driver JSONs (no checkpoint recompute, no engine
geometry literals — all upstream numbers were produced by the per-driver probes which already
sourced geometry from registry.toml via hexo_rl.encoding). This probe is a META-analysis: it
does NOT re-measure a driver; it tests the ORDERING claims that the dispatcher hypothesized.

The dispatcher stack: D1 -> D3 -> D5
  D1: value can't value concentration  ->
  D3: search/targets don't credit fork-building (because value drives search)  ->
  D5: self-play reinforces spread, never punished internally.

But the driver verdicts are: D1 OUT, D2 OUT, D3 OUT, D4 OUT, D5 INCONCLUSIVE. So NO node in the
stack is LIT. The ordering question therefore reframes: given the turn-vs-ply credit gap (a STATIC
depth-1 engine-credit fact that sits structurally upstream of BOTH value and search), is the
credit gap the true root, with D1 its (non-firing) symptom? Could D3 be upstream of D1? Is D5 the
external readout of D1/D3 rather than a driver?

DISCRIMINATING TESTS (all from banked data):
  T1  CREDIT-GAP CONSTANCY: is the depth-1 credit gap STATIC across the arc (=> a standing
      structural fact upstream of the trend) or does it TRACK the over-spread arc (=> it is the
      arc DRIVER)?  Source: forkredundancy.json {credit_gap, ply_blind, thin, turn_fork}.
  T2  D1-UPSTREAM TEST: if D1 (value-conc ceiling) were the root, AUC_conc must FALL to <=0.60 as
      over-spread rises. Correlate AUC_conc_median vs mover_ncomp across the arc; report whether
      value-ranking DEGRADES with spread (D1-driver signature) or stays a clean high signal
      (D1-readout / D1-not-a-driver).  Source: d1_value_conc.json + overspread.json.
  T3  D3-vs-D1 ORDERING: the stack says value drives search, so if value ranks concentration well
      (D1 clean) but search still spreads, D3 would be upstream of the spread. Test the D3
      fork-affinity arc: does target fork-affinity FALL as spread rises (D3-driver) or stay HIGH
      and peak with value sharpness at 75k (D3-readout of the same sharpness wave)?
      Source: d3_fork_affinity.json (mcts + policy_prior) + inwindow_policy_value.json (value).
  T4  75k CO-MOVEMENT: the 75k sharpness peak appears INDEPENDENTLY in value (value_mean_win,
      AUC), policy-prior fork-mass, and MCTS fork-affinity. If value/search/fork-affinity all
      peak TOGETHER at 75k while over-spread keeps rising monotonically, then value & search are
      a COUPLED sharpness wave riding ON TOP of a monotone spread substrate — the spread is NOT
      generated by value or search (they'd have to be monotone to drive a monotone trend). This
      directly attacks the "value-first" arrow.
  T5  D5-AS-READOUT: D5 decline-leg tracks WR with spearman +/-1 but n=3 collinear; Part 2
      (losses are spread-force) is instrument-blocked. Classify D5 as DRIVER vs READOUT by asking:
      does D5 add an arc-GENERATING mechanism, or only an external WR co-movement? (qualitative,
      from d5_coadapt.json structure.)

OUTPUT: investigation/overspread_2026-06-08/ordering_redteam.json + a verdict dict printed.
"""
from __future__ import annotations

import json
from pathlib import Path

import numpy as np

INV = Path("investigation/overspread_2026-06-08")
COH = Path("investigation/coherence_2026-06-08")


def load(p: Path) -> dict:
    with open(p) as fh:
        return json.load(fh)


def pearson(x, y):
    x = np.asarray(x, float)
    y = np.asarray(y, float)
    if len(x) < 2 or np.std(x) == 0 or np.std(y) == 0:
        return float("nan")
    return float(np.corrcoef(x, y)[0, 1])


def spearman(x, y):
    x = np.asarray(x, float)
    y = np.asarray(y, float)
    if len(x) < 2:
        return float("nan")
    rx = np.argsort(np.argsort(x))
    ry = np.argsort(np.argsort(y))
    return pearson(rx, ry)


def main():
    fork = load(INV / "forkredundancy.json")
    d1 = load(INV / "d1_value_conc.json")
    d3 = load(INV / "d3_fork_affinity.json")
    d5 = load(INV / "d5_coadapt.json")
    overspread = load(COH / "overspread.json")
    inwin = load(COH / "inwindow_policy_value.json")

    out = {"encoding": "v6_live2", "tests": {}}

    # ---- T1: credit-gap constancy (is the depth-1 gap the arc driver or a static fact?) ----
    fb = fork["buckets"]
    steps_f = [b["step"] for b in fb]
    credit_gap = [b["credit_gap"] for b in fb]
    ply_blind = [b["ply_blind"] for b in fb]
    thin = [b["thin"] for b in fb]
    turn_fork = [b["turn_fork"] for b in fb]
    os_ncomp_3 = [b["mover_ncomp"] for b in overspread["buckets"]]  # 30k/53k/87.5k aligned
    out["tests"]["T1_credit_gap_constancy"] = {
        "steps": steps_f,
        "credit_gap": credit_gap,
        "credit_gap_range": [min(credit_gap), max(credit_gap)],
        "credit_gap_is_static": (max(credit_gap) - min(credit_gap)) < 1e-9,
        "ply_blind": ply_blind,
        "ply_blind_range": [min(ply_blind), max(ply_blind)],
        "thin": thin,
        "turn_fork": turn_fork,
        "overspread_ncomp_same_buckets": os_ncomp_3,
        "overspread_ncomp_rise_pct": 100.0 * (os_ncomp_3[-1] - os_ncomp_3[0]) / os_ncomp_3[0],
        "corr_creditgap_vs_ncomp": pearson(credit_gap, os_ncomp_3),
        "interpretation": (
            "credit_gap STATIC at 1.0 (range 0) while ncomp rises +58% => the depth-1 credit gap "
            "is a STANDING structural fact, NOT the arc-generating driver. It sits upstream of "
            "BOTH value and search as a constant: no hard turn-fork/concentration credit anywhere "
            "in the value path, at EVERY checkpoint. A constant cannot generate a monotone trend "
            "(same logic that ruled D4 OUT), so the credit gap is a STANDING-CONDITION root, not "
            "the TREND driver."
        ),
    }

    # ---- T2: D1-upstream test (does value-ranking DEGRADE with spread?) ----
    d1c = d1["checkpoints"]
    steps_d1 = [c["step"] for c in d1c]
    auc_med = [c["auc_conc_ncomp_median"] for c in d1c]
    auc_ter = [c["auc_conc_ncomp_tertile"] for c in d1c]
    auc_largest = [c["auc_conc_largest_frac"] for c in d1c]
    # over-spread interpolated to the 11-rung ladder is not banked; use the 3 anchored buckets
    # for the spread axis and compare the trend SIGN. Use ncomp at matching/nearest steps.
    # Build a coarse spread proxy per ladder step via linear interp of the 3 anchored buckets.
    os_steps_3 = overspread["buckets"]
    sx = [b["step"] for b in os_steps_3]
    sy = [b["mover_ncomp"] for b in os_steps_3]
    spread_at = [float(np.interp(s, sx, sy)) for s in steps_d1]
    out["tests"]["T2_d1_upstream"] = {
        "steps": steps_d1,
        "auc_conc_median": auc_med,
        "auc_conc_median_range": [min(auc_med), max(auc_med)],
        "auc_conc_median_min": min(auc_med),
        "auc_conc_tertile_mean": float(np.mean(auc_ter)),
        "lit_floor": 0.60,
        "ever_breaches_floor": any(a <= 0.60 for a in auc_med),
        "arc_slope_per_1k": float(np.polyfit(steps_d1, auc_med, 1)[0] * 1000),
        "spread_proxy_at_step": spread_at,
        "corr_auc_vs_spread": pearson(auc_med, spread_at),
        "interpretation": (
            "AUC_conc never <=0.60 (min 0.640 @90k), mild decline slope -0.00117/1k from a high "
            "0.75 ceiling. Negative corr_auc_vs_spread means value-ranking softens AS spread rises "
            "— BUT it stays a CLEAN high signal (>>0.60, never chance). If D1 were the upstream "
            "DRIVER, AUC would have to CROSS the 0.60 floor as spread grew; it never does. So value "
            "is NOT blind to concentration even at peak spread => D1 is NOT the value-first root. "
            "The value-first arrow of the stack is BROKEN: value sees concentration, so spread is "
            "produced UPSTREAM of value ranking, not by a value ceiling."
        ),
    }

    # ---- T3: D3 fork-affinity arc (driver vs readout) ----
    mcts = d3["mcts"]
    pol = d3["policy_prior_all_ckpts"]
    null_mass = d3["uniform_fork_mass"]
    mcts_steps = [m["step"] for m in mcts]
    mcts_mass = [m["mcts_fork_mass"] for m in mcts]
    pol_steps = [p["step"] for p in pol]
    pol_mass = [p["policy_fork_mass"] for p in pol]
    out["tests"]["T3_d3_fork_affinity"] = {
        "null_uniform_mass": null_mass,
        "mcts_steps": mcts_steps,
        "mcts_fork_mass": mcts_mass,
        "mcts_x_null": [m / null_mass for m in mcts_mass],
        "mcts_peak_step": mcts_steps[int(np.argmax(mcts_mass))],
        "mcts_arc_delta_30k_to_87k": mcts_mass[-1] - mcts_mass[0],
        "policy_steps": pol_steps,
        "policy_fork_mass": pol_mass,
        "policy_peak_step": pol_steps[int(np.argmax(pol_mass))],
        "policy_x_null_min": min(pol_mass) / null_mass,
        "policy_arc_delta": pol_mass[-1] - pol_mass[0],
        "interpretation": (
            "Fork-affinity HIGH (MCTS 155-233x null, policy ~65-114x null) and DOES NOT fall — both "
            "instruments PEAK at 75k then dip, net ~flat. If D3 (target doesn't credit forks) were "
            "upstream of the spread, fork-affinity would be LOW and FALLING as spread rises; it is "
            "neither. The 75k peak in fork-affinity COINCIDES with the 75k value/policy sharpness "
            "peak => fork-affinity is a READOUT of the shared sharpness wave, not an independent "
            "spread driver. D3 is downstream-of/coupled-to value sharpness, NOT upstream of it."
        ),
    }

    # ---- T4: 75k co-movement of value, policy-fork, mcts-fork vs MONOTONE over-spread ----
    iw = inwin["checkpoints"]
    iw_steps = [c["step"] for c in iw]
    value_mean = [c["value_mean_win"] for c in iw]
    value_auc = [c["value_auc_won_vs_notwon"] for c in iw]
    pwin = [c["p_win"] for c in iw]
    # peak-at-75k flags
    def peaks_at(steps, vals, target=75000):
        return steps[int(np.argmax(vals))] == target
    # over-spread monotonicity across the 3 anchored buckets
    os_mono = all(sy[i] < sy[i + 1] for i in range(len(sy) - 1))
    out["tests"]["T4_75k_comovement"] = {
        "iw_steps": iw_steps,
        "value_mean_win": value_mean,
        "value_mean_peaks_75k": peaks_at(iw_steps, value_mean),
        "value_auc_peaks_75k": peaks_at(iw_steps, value_auc),
        "policy_pwin_peaks_75k": peaks_at(iw_steps, pwin),
        "policy_fork_peaks_75k": pol_steps[int(np.argmax(pol_mass))] == 75000,
        "mcts_fork_peaks_75k": mcts_steps[int(np.argmax(mcts_mass))] == 75000,
        "overspread_monotone_rising": os_mono,
        "overspread_buckets": sy,
        "interpretation": (
            "value_mean, value_AUC, policy p_win, policy-fork-mass, AND MCTS-fork-mass ALL peak at "
            "75k (the §D-FRAGILITY/§D-COHERENCE sharpness peak), while over-spread (ncomp 14->22) "
            "rises MONOTONICALLY through 75k with no peak. A monotone trend CANNOT be generated by "
            "a non-monotone (peaked) signal. Therefore value-sharpness and search-fork-affinity are "
            "a COUPLED wave riding ON TOP of the monotone spread substrate — they are NOT the "
            "generators of the spread. This is the decisive blow to the value-first (D1->D3) arrow: "
            "the spread substrate is upstream of BOTH value and search co-adaptation."
        ),
    }

    # ---- T5: D5 driver-vs-readout classification ----
    dleg = d5["decline_leg"]
    out["tests"]["T5_d5_readout"] = {
        "decline_leg_spearman_ncomp": dleg["mover_ncomp"]["spearman"],
        "decline_leg_n": dleg["mover_ncomp"]["n"],
        "part2_testable": d5["part2"]["testable"],
        "part2_reason": d5["part2"]["reason"],
        "interpretation": (
            "D5 decline-leg tracks WR (spearman +/-1) but n=3 collinear and Part 2 (losses are "
            "spread-force) is instrument-blocked. D5 supplies NO arc-generating mechanism — it is "
            "the EXTERNAL readout (SealBot WR falls because the uncorrected spread is externally "
            "punished by a compact finisher). D5 is a terminal symptom-amplifier / readout, not a "
            "root. It is the 'why it isn't fixed internally', not the 'why it starts'."
        ),
    }

    # ---- SYNTHESIS: the ordering verdict ----
    out["synthesis"] = {
        "stack_hypothesized": "D1 -> D3 -> D5 (value-first)",
        "node_lit_status": {"D1": "OUT", "D2": "OUT", "D3": "OUT", "D4": "OUT", "D5": "INCONCLUSIVE"},
        "value_first_arrow": "BROKEN",
        "value_first_arrow_evidence": (
            "D1 OUT (AUC_conc 0.64-0.75, never <=0.60) => value SEES concentration. T2: value-ranking "
            "never crosses the LIT floor even at peak spread. T4: value/policy/MCTS-fork all PEAK at "
            "75k while spread is MONOTONE => value+search are a coupled sharpness wave, not the "
            "monotone-trend generator. The 'value can't value concentration' premise is false."
        ),
        "most_upstream_node": (
            "STANDING depth-1 credit gap (turn-vs-ply): no hard turn-fork/concentration credit "
            "anywhere in the value/target path, STATIC (credit_gap=1.0, ply_blind ~0.93-0.98 flat) "
            "at EVERY checkpoint. It is upstream of value(D1) and search(D3) as a permanent "
            "structural condition — but being STATIC it is a standing-condition, not the TREND "
            "driver (same constancy logic that ruled D4 OUT). The TREND itself (own-fragmentation "
            "14->22) is the §D-COHERENCE self-play play-structure drift; D5 is the external readout."
        ),
        "ordering_corrected": (
            "[STANDING ROOT: depth-1 credit gap, static] -> [TREND: self-play own-force "
            "fragmentation drift, the §D-COHERENCE WHAT] -> [D5: no internal compact counter-pressure "
            "=> external SealBot-WR readout falls]. D1 and D3 are NOT in the causal chain as drivers: "
            "value ranks concentration well (D1 clean readout), search credits forks well (D3 clean "
            "readout); both are coupled sharpness signals downstream of the spread substrate, not "
            "its cause. The hypothesized value-first D1->D3->D5 is REJECTED."
        ),
        "fix_sequence": (
            "NOT value-first (D1 not lit, not upstream). Value+search are CLEAN signals to lean ON. "
            "Fix the STANDING ROOT first: install a hard turn-correct fork/concentration credit "
            "(promote count_winning_turns into the value/target path so the spread is internally "
            "punished) — a target-shaping/reward change, gated against the §175/§S181 colony pole "
            "and re-measured on SealBot-WR. Then D5 (compact-reference self-play regularizer) as "
            "the co-adaptation backstop. D1/D3 need NO patch — they already see concentration/forks."
        ),
    }

    with open(INV / "ordering_redteam.json", "w") as fh:
        json.dump(out, fh, indent=2)

    # print a compact verdict
    print("=== §D-OVERSPREAD ORDERING RED-TEAM ===")
    print(f"T1 credit_gap static: {out['tests']['T1_credit_gap_constancy']['credit_gap_is_static']} "
          f"(range {out['tests']['T1_credit_gap_constancy']['credit_gap_range']}) "
          f"vs ncomp +{out['tests']['T1_credit_gap_constancy']['overspread_ncomp_rise_pct']:.0f}%")
    print(f"T2 AUC_conc min {out['tests']['T2_d1_upstream']['auc_conc_median_min']:.3f} "
          f"breaches 0.60 floor: {out['tests']['T2_d1_upstream']['ever_breaches_floor']} "
          f"(slope/1k {out['tests']['T2_d1_upstream']['arc_slope_per_1k']:.5f})")
    print(f"T3 MCTS fork x-null {out['tests']['T3_d3_fork_affinity']['mcts_x_null']} "
          f"peak@{out['tests']['T3_d3_fork_affinity']['mcts_peak_step']}")
    print(f"T4 peaks@75k: value_mean={out['tests']['T4_75k_comovement']['value_mean_peaks_75k']} "
          f"value_auc={out['tests']['T4_75k_comovement']['value_auc_peaks_75k']} "
          f"pol_fork={out['tests']['T4_75k_comovement']['policy_fork_peaks_75k']} "
          f"mcts_fork={out['tests']['T4_75k_comovement']['mcts_fork_peaks_75k']} | "
          f"overspread monotone={out['tests']['T4_75k_comovement']['overspread_monotone_rising']}")
    print(f"VALUE-FIRST ARROW: {out['synthesis']['value_first_arrow']}")
    print(f"MOST-UPSTREAM: {out['synthesis']['most_upstream_node'][:120]}...")
    print(f"wrote {INV / 'ordering_redteam.json'}")


if __name__ == "__main__":
    main()
