#!/usr/bin/env python3
"""§D-VALPROBE Phase 4 — leak-free self-play fixture generator.

WHY: the corpus calibration ladder (E1 BENIGN SHARPENING) measured the value
head on the bootstrap corpus — ~62% of the 50k training mix and compact-style
scraped games. Two caveats (C1 train-distribution fit, C2 wrong regime) keep
that result from being load-bearing. This script builds the HONEST fixture:

  * LEAK-FREE — replay-buffer rows were trained on; instead, FRESH games are
    generated post-training at the FINAL checkpoint via the standard WorkerPool
    self-play path (the live spread regime; v6_live2_ls routes through the Rust
    legal-set multi-window machinery, NOT the single-window ModelPlayer —
    §9.10).
  * TRAINING-ROW FORMAT — positions are rebuilt by replaying each game's move
    list through Board.with_encoding_name(...); GameState.to_tensor() emits the
    (K, 18, S, S) per-cluster views and the registry kept_plane_indices slice
    reproduces the exact wire rows the trainer supervises (K rows per position,
    one z per row, mover-perspective).
  * PERSPECTIVE-CORRECT — z labels derive from the game_complete winner spec
    (0=P0/x ⇔ board.current_player==1 to move first; 1=P1/o; -1=draw); an
    in-script self-check forwards the GENERATING checkpoint over the slice and
    requires sign_acc >= --min-sign-acc (a flipped extraction reads ~1-acc).
  * FALSE-LABEL HYGIENE — ply-capped games are horizon truncation with no real
    outcome (DRAW-MASK rationale); they are dropped, and the drop is counted.

RESIDUAL ASYMMETRY (state honestly, do not hide): the fixture is generated BY
the tip checkpoint, so earlier ladder rungs are scored slightly off THEIR own
self-play distribution. The question under test is whether the CURRENT head is
healthy on the CURRENT regime, so this is acceptable — and the ladder's anchor
rung makes the asymmetry measurable (see the red-team check).

Reproducibility: python/numpy/torch seeds are fixed, but the Rust worker RNG
is not seed-pluggable from this surface — the FROZEN ARTIFACT (the saved npz)
is the fixed-slice discipline, identical methodology to the corpus fixture.

Run (vast, where the 50k checkpoint lives):
  .venv/bin/python scripts/diagnosis/selfplay_fixture_gen.py \
    --checkpoint checkpoints/checkpoint_00050000.pt \
    --variant v6_live2_ls_ab --n-games 150 \
    --out data/selfplay_fixture_v6_live2_ls_50k.npz
"""
from __future__ import annotations

import argparse
import json
import pathlib
import re
import sys
import time
from typing import Dict, List, Optional, Tuple

import numpy as np

ROOT = pathlib.Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

_MOVE_RE = re.compile(r"^\((-?\d+),(-?\d+)\)$")

# Terminal reasons whose outcome is a REAL game result. ply_cap is horizon
# truncation — its value label is false (DRAW-MASK rationale) and excluded.
KEEP_TERMINAL_REASONS = ("six_in_a_row", "colony", "other_draw")


# ── pure kernels (tested in tests/test_selfplay_fixture_gen.py) ──────────────


def parse_moves_list(moves_list: List[str]) -> List[Tuple[int, int]]:
    """Parse pool.py game_complete ``moves_list`` strings '(q,r)' to int pairs."""
    out: List[Tuple[int, int]] = []
    for s in moves_list:
        m = _MOVE_RE.match(s)
        if not m:
            raise ValueError(f"unparseable move string: {s!r}")
        out.append((int(m.group(1)), int(m.group(2))))
    return out


def z_for_mover(winner_int: int, mover: int) -> float:
    """Mover-perspective outcome z for a position where ``mover`` is to move.

    ``winner_int`` follows the game_complete payload spec (pool.py):
    0 = P0/x (the side moving when board.current_player == 1),
    1 = P1/o, -1 = draw.
    """
    if winner_int == -1:
        return 0.0
    winner_player = 1 if winner_int == 0 else -1
    return 1.0 if mover == winner_player else -1.0


def keep_game(game: Dict) -> bool:
    """Keep games with a real outcome and a non-empty move list."""
    return bool(game.get("moves_list")) and (
        game.get("terminal_reason") in KEEP_TERMINAL_REASONS
    )


# ── game capture (renderer on the monitoring event bus) ──────────────────────


class GameCapture:
    """Event renderer that collects every game_complete payload."""

    def __init__(self) -> None:
        self.games: List[Dict] = []

    def on_event(self, payload: Dict) -> None:
        if payload.get("event") == "game_complete":
            self.games.append({
                "winner": payload.get("winner"),
                "moves_list": payload.get("moves_list") or [],
                "terminal_reason": payload.get("terminal_reason"),
                "plies": payload.get("moves"),
            })


# ── generation (standard WorkerPool self-play path) ──────────────────────────


def generate_games(checkpoint: str, variant: str, n_games: int,
                   encoding_override: Optional[str]) -> Tuple[List[Dict], Dict]:
    import torch
    from engine import ReplayBuffer
    from hexo_rl.encoding import resolve_encoding_for_eval
    from hexo_rl.model.network import HexTacToeNet
    from hexo_rl.monitoring.events import register_renderer
    from hexo_rl.selfplay.pool import WorkerPool
    from hexo_rl.utils.config import load_config
    from hexo_rl.utils.device import best_device

    base = ["configs/model.yaml", "configs/training.yaml", "configs/selfplay.yaml"]
    cfg = load_config(*base, f"configs/variants/{variant}.yaml")
    spec = resolve_encoding_for_eval(checkpoint, encoding_override)
    cfg["encoding"] = spec.name
    for stale_key in ("board_size", "in_channels", "n_planes",
                      "cluster_window_size", "cluster_threshold",
                      "legal_move_radius"):
        cfg.pop(stale_key, None)

    device = best_device()
    torch.set_float32_matmul_precision("high")
    if device.type == "cuda":
        torch.backends.cudnn.benchmark = True

    mcfg = cfg.get("model", {})
    model = HexTacToeNet(
        board_size=spec.trunk_size,
        in_channels=spec.n_planes,
        filters=int(mcfg.get("filters", 128)),
        res_blocks=int(mcfg.get("res_blocks", 12)),
        encoding=spec.name,
    ).to(device)
    ckpt = torch.load(checkpoint, map_location=device, weights_only=False)
    state = ckpt.get("model_state") if isinstance(ckpt, dict) else None
    if state is None:
        state = ckpt.get("model_state_dict") if isinstance(ckpt, dict) else ckpt
    if state is None:
        state = ckpt
    model.load_state_dict(state, strict=False)
    model.eval()

    capture = GameCapture()
    register_renderer(capture)

    buffer = ReplayBuffer(capacity=200_000, encoding=spec.name)
    pool = WorkerPool(model, cfg, device, buffer, n_workers=None)
    pool.start()
    t0 = time.perf_counter()
    try:
        while pool.games_completed < n_games:
            time.sleep(2.0)
            g = pool.games_completed
            if g > 0 and g % 20 == 0:
                print(f"  [gen] {g}/{n_games} games", flush=True)
    finally:
        pool.stop()
    elapsed = time.perf_counter() - t0

    stats = {
        "encoding": spec.name,
        "n_games_completed": pool.games_completed,
        "x_wins": pool.x_wins, "o_wins": pool.o_wins, "draws": pool.draws,
        "elapsed_sec": round(elapsed, 1),
        "n_workers": cfg.get("selfplay", {}).get("n_workers"),
    }
    return capture.games, stats


# ── extraction (replay move lists → per-cluster training rows) ───────────────


def extract_rows(games: List[Dict], encoding: str):
    """Replay each kept game; emit (K rows, z, occupancy, k_count, ply) per position."""
    from engine import Board
    from hexo_rl.encoding import lookup
    from hexo_rl.env.game_state import GameState

    spec = lookup(encoding)
    kept = list(spec.kept_plane_indices)

    rows_states: List[np.ndarray] = []
    rows_z: List[float] = []
    rows_k: List[int] = []
    rows_ply: List[int] = []
    rows_game: List[int] = []
    n_dropped = 0
    for gi, game in enumerate(games):
        if not keep_game(game):
            n_dropped += 1
            continue
        moves = parse_moves_list(game["moves_list"])
        winner_int = int(game["winner"])
        board = Board.with_encoding_name(encoding)
        state = GameState.from_board(board)
        for ply, (q, r) in enumerate(moves):
            mover = int(board.current_player)
            tensor, _centers = state.to_tensor()      # (K, 18, S, S) f16
            k = tensor.shape[0]
            z = z_for_mover(winner_int, mover)
            for view in tensor[:, kept]:              # K × (C, S, S)
                rows_states.append(np.asarray(view, dtype=np.float16))
                rows_z.append(z)
                rows_k.append(k)
                rows_ply.append(ply)
                rows_game.append(gi)
            state = state.apply_move(board, q, r)
    return (
        np.stack(rows_states) if rows_states else np.empty((0,)),
        np.asarray(rows_z, dtype=np.float32),
        np.asarray(rows_k, dtype=np.int32),
        np.asarray(rows_ply, dtype=np.int32),
        np.asarray(rows_game, dtype=np.int32),
        n_dropped,
    )


# ── main ─────────────────────────────────────────────────────────────────────


def main() -> int:
    ap = argparse.ArgumentParser(
        description="Leak-free self-play fixture generator (§D-VALPROBE Phase 4)")
    ap.add_argument("--checkpoint", required=True,
                    help="tip checkpoint that GENERATES the fixture games")
    ap.add_argument("--variant", default="v6_live2_ls_ab",
                    help="variant config = the run's standard self-play config")
    ap.add_argument("--encoding", default=None,
                    help="override encoding (default: resolve from checkpoint)")
    ap.add_argument("--n-games", type=int, default=150)
    ap.add_argument("--n-positions", type=int, default=4000,
                    help="fixed slice size (matches the corpus probe)")
    ap.add_argument("--seed", type=int, default=20260611,
                    help="slice seed (matches the corpus probe discipline)")
    ap.add_argument("--min-sign-acc", type=float, default=0.55,
                    help="perspective self-check floor (generating ckpt on slice)")
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    import random

    import torch
    random.seed(args.seed)
    np.random.seed(args.seed)
    torch.manual_seed(args.seed)

    print(f"[fixture-gen] ckpt={args.checkpoint} variant={args.variant} "
          f"n_games={args.n_games} seed={args.seed}", flush=True)
    games, gen_stats = generate_games(
        args.checkpoint, args.variant, args.n_games, args.encoding)
    encoding = gen_stats["encoding"]
    print(f"[fixture-gen] captured {len(games)} games: {gen_stats}", flush=True)

    states, z, k_counts, plies, game_ids, n_dropped = extract_rows(games, encoding)
    print(f"[fixture-gen] extracted {len(z)} rows from "
          f"{len(games) - n_dropped} kept games ({n_dropped} dropped: "
          f"ply_cap/empty)", flush=True)
    if len(z) < args.n_positions:
        print(f"[fixture-gen] FAIL: only {len(z)} rows < --n-positions "
              f"{args.n_positions}; raise --n-games", flush=True)
        return 2

    rng = np.random.default_rng(args.seed)
    idx = rng.choice(len(z), size=args.n_positions, replace=False)
    idx.sort()
    states, z = states[idx], z[idx]
    k_counts, plies, game_ids = k_counts[idx], plies[idx], game_ids[idx]

    # perspective self-check: forward the GENERATING checkpoint over the slice
    from hexo_rl.eval.checkpoint_loader import load_model_with_encoding
    from hexo_rl.utils.device import best_device
    from scripts.diagnosis.value_calibration_ladder import compute_metrics, forward_values
    device = best_device()
    model, _s, _label = load_model_with_encoding(pathlib.Path(args.checkpoint), device)
    v, _logits = forward_values(model, states.astype(np.float32), 512, str(device))
    m = compute_metrics(v, z, draw_band=0.10)
    print(f"[self-check] generating-ckpt sign_acc={m['sign_acc']:.3f} "
          f"(floor {args.min_sign_acc}) value_mse={m['value_mse']:.4f}", flush=True)
    if not (m["sign_acc"] >= args.min_sign_acc):
        print("[self-check] FAIL — labels likely perspective-flipped; "
              "fixture NOT written", flush=True)
        return 1

    out = pathlib.Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    np.savez_compressed(
        out, states=states, outcomes=z,
        k_counts=k_counts, plies=plies, game_ids=game_ids,
    )
    kept_games = [g for g in games if keep_game(g)]
    lengths = [g["plies"] for g in kept_games]
    sidecar = {
        "generator": "scripts/diagnosis/selfplay_fixture_gen.py",
        "checkpoint": args.checkpoint,
        "variant": args.variant,
        "encoding": encoding,
        "seed": args.seed,
        "n_positions": int(len(z)),
        "n_games_kept": len(kept_games),
        "n_games_dropped": n_dropped,
        "generation": gen_stats,
        "self_check": {"sign_acc": m["sign_acc"], "floor": args.min_sign_acc},
        "k_distribution": {str(k): int(c) for k, c in
                           zip(*np.unique(k_counts, return_counts=True))},
        "game_length_plies": {
            "mean": float(np.mean(lengths)) if lengths else 0.0,
            "min": int(min(lengths)) if lengths else 0,
            "max": int(max(lengths)) if lengths else 0,
        },
        "terminal_reasons": {tr: sum(1 for g in kept_games
                                     if g["terminal_reason"] == tr)
                             for tr in KEEP_TERMINAL_REASONS},
        "residual_asymmetry_note": (
            "fixture generated BY the tip checkpoint; earlier rungs are scored "
            "slightly off THEIR own distribution (acceptable: the question is "
            "whether the CURRENT head is healthy on the CURRENT regime)"),
    }
    out.with_suffix(".json").write_text(json.dumps(sidecar, indent=2))
    print(f"[fixture-gen] wrote {out} (+ sidecar {out.with_suffix('.json')})",
          flush=True)
    return 0


if __name__ == "__main__":
    sys.exit(main())
