//! Cross-language temperature-parity regression guard (D-TEMPDECAY, 2026-06-12).
//!
//! Pins that the Rust training-path temperature reproduces the SAME golden table
//! that the Python eval/bot path checks (`tests/test_temperature.py::
//! test_python_matches_parity_golden`). Both read the SAME fixture
//! `tests/fixtures/temperature_parity_golden.csv` (generated by
//! `tests/fixtures/gen_temperature_parity_golden.py`). If either the formula or
//! the ply→compound-turn clock drifts in one language, this test (or its Python
//! twin) fires.
//!
//! Driven by PLY so the ply→cm clock (`cm = 0 if ply==0 else div_ceil(ply,2)`,
//! matching `worker_loop/inner.rs:896`) is part of the contract, including the
//! ply-0 special case and the ply1/ply2 same-cm boundary.

use engine::game_runner::compute_move_temperature;

fn ply_to_compound_move(ply: usize) -> usize {
    if ply == 0 { 0 } else { ply.div_ceil(2) }
}

#[test]
fn rust_matches_temperature_parity_golden() {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../tests/fixtures/temperature_parity_golden.csv"
    );
    let text = std::fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("cannot read parity golden fixture {path}: {e}"));

    let mut checked = 0_usize;
    for line in text.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let cols: Vec<&str> = line.split(',').collect();
        assert_eq!(cols.len(), 4, "bad fixture row: {line:?}");
        let ply: usize = cols[0].parse().expect("ply");
        let threshold: usize = cols[1].parse().expect("threshold");
        let temp_min: f32 = cols[2].parse().expect("temp_min");
        let expected: f32 = cols[3].parse().expect("expected_tau");

        let cm = ply_to_compound_move(ply);
        let got = compute_move_temperature(cm, threshold, temp_min);
        assert!(
            (got - expected).abs() < 1e-6,
            "ply={ply} (cm={cm}) thr={threshold} tmin={temp_min}: got {got}, golden {expected}"
        );
        checked += 1;
    }
    assert!(checked > 0, "parity golden fixture had no data rows");
}
